### ISSUE TITLE
Get Index button does nothing with Mongo 3

### ISSUE THREAD

**Issue by dustinblackman** [jeromelebel/MongoHub-Mac#199]
When you open a collection, click the index tab above query box, and then hit Get Index returns no data in Mongo 3.0.0-RC8 even though the index's are reported in the stats window.  This is with MongoHub 3.1b3.

**Comment by MRigal** [comment]
+1, problem confirmed

**Comment by jeromelebel** [comment]
any messages in the log window?

**Comment by MRigal** [comment]
no, it remains empty...

**Comment by jeromelebel** [comment]
I can't reproduce the issue.

**Comment by Icehunter** [comment]
I use production 3.0.1 (mongodb) and have this issue as well using beta 4 and master branch compiles. I also can't open documents when double clicking on them but I'll find a proper issue to report that.

**Comment by jeromelebel** [comment]
thank. I need at least an error message (in the console of OS X, or somewhere else). Or I need a way to add a document like that in my own collection. Or I need a server where I can connect to reproduce this issue.

**Comment by Icehunter** [comment]
My knowledge of xcode so far and programming on OSX in general is just opening the project and pressing build. I tried attaching to process as well as pressing the "play" button but nothing appears in the console at the lower right.

Is there something I should do differently to get console output?

**Comment by MRigal** [comment]
Actually, since I upgraded to 3.0.1 and using MongoHub 3.1b4, I do not have the issue anymore ! Are you sure @Icehunter to have the problem with that configuration ? I had it before, but it seems solved in my case...

**Comment by Icehunter** [comment]
@MRigal Not quite sure. When I download the tagged source at 3.1b4 or I go through master it always asks me to update the project because of some config issues.

I have Yosemite and the latest xcode/updates. When I build it after that there's no issues I can see so far other than dealing with indexes/opening a document into the edit view.

It also doesn't pipe any errors to the console but this is the first project I've ever built with xcode as I mostly build c# desktop applications and node services.

**Comment by jeromelebel** [comment]
Can you try with 3.1.3?

**Comment by Icehunter** [comment]
It fixes the issue of not being able to open a document and save/delete but getting the indexes still fails. I also deleted the app/preferences/plists along with the git folder and recloned; but I still have the same issue.

**Comment by jeromelebel** [comment]
Can someone try: https://mongohub.s3.amazonaws.com/MongoHub-issue-199.zip ?

I would need the mongohub log from the console.

**Comment by jeromelebel** [comment]
you can contact me on skype: lebel.jerome

**Comment by MRigal** [comment]
It is actually fixed in my case since 3.1.3
Am 30.03.2015 13:06 schrieb "Jérôme Lebel" <notifications@github.com>:

**Comment by jeromelebel** [comment]
Should be fixed in 3.1.4. I let you close this issue if it works for you.

**Comment by MRigal** [comment]
I don't know who is "you", but it also works in 3.1.4 for me

**Comment by jeromelebel** [comment]
Mostly the owner of the issue (to close the bug), and anyone who still had the issue with 3.1.3 :)
